name: ci_windows

env:
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_windows.yml"


jobs:

  windows:
    runs-on: windows-latest
    env:
      CMAKE_GENERATOR: "MinGW Makefiles"

    steps:
    - uses: actions/checkout@v2

    # GitHub Actions windows image doesn't have WSL, so use version without need to patch
    - run: cmake -B build -Darith=d -Dparallel:BOOL=false "-DMUMPS_UPSTREAM_VERSION=5.3.5"
    - run: cmake --build build
    - run: ctest --test-dir build --preset default
